### PR TITLE
 Add the platformer microgame used for Unity tutorial in Research/sl121/

### PR DESCRIPTION
**Pull request by TongxueLiu**
Platformer microgame used for Unity tutorial

### CODE REVIEW

**Comment by xucharles97** [comment]
The Sprint 1 Unity Tutorial under Research/sl121 looks good. Not sure what the other "Sprint 1 Unity Tutorial" folder in the main directory is though. Either rename it and move it under your research folder if it is different from the other one or delete it

**Comment by TongxueLiu** [comment]
> The Sprint 1 Unity Tutorial under Research/sl121 looks good. Not sure what the other "Sprint 1 Unity Tutorial" folder in the main directory is though. Either rename it and move it under your research folder if it is different from the other one or delete it

Are we able to remove this folder on the website, or only by Bash?

**Comment by xucharles97** [comment]
I don't think there's a way to do it from github (although I could be wrong). I think it would probably just be easier to do it on your command line

**Comment by xucharles97** [comment]
Rename the main folder as just your netid then add a separate tutorial folder beneath that

**Pull request merged**
