### PR TITLE
Manager class

### PR DESCRIPTION
**Pull request by willc-1**
create manager class with instance variables, getters, and setters

### CODE REVIEW

**Comment by xucharles97** [comment]
Looks good. Going to wait until everyone else adds their classes before merging so I can ensure compatability

**Comment by xucharles97** [comment]
Move the manager class under Project

**Comment by williamc-1** [comment]
> Move the manager class under Project



> Move the manager class under Project

Can I just cancel this

**Comment by willc-1** [comment]
> Move the manager class under Project

Can I just cancel this pull request and make a new one under the project folder?

**Comment by xucharles97** [comment]
ok

**Pull request closed without merging**
